spring:
  profiles:
    active:
    - dev
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis 配置文件
  type-aliases-package: com.fly.springcloud.entity  #将entity包下的类别名
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  profiles: dev
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root
    password: mysql
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址

info: #追加信息描述,用于微服务注册中心的提示信息
  app.name: fly-microservicecloud
  company.name: www.flyzgq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}

---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml #mybatis 配置文件
  type-aliases-package: com.fly.springcloud.entity  #将entity包下的类别名
  mapper-locations: classpath:mybatis/mapper/**/*.xml #mapper映射文件

spring:
  profiles: test
  application:
    name: microservicecloud-config-dept-client
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/clouddb01
    username: root
    password: mysql
    #   数据源其他配置
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    #   配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall,slf4j
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
eureka:
  client: #客户端注册进eureka服务列表内
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: microservicecloud-dept8001 #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示ip地址

info: #追加信息描述,用于微服务注册中心的提示信息
  app.name: fly-microservicecloud
  company.name: www.flyzgq.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}